### ISSUE TITLE
NxM Axis Setup function

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#11]
We need a way to initialize M number of Ribbons as atom horizontal axes

**Comment by tkeyes25** [comment]
@robobenklein Next issue to maybe work on? Could you go into more detail if so

**Comment by robobenklein** [comment]
Notes:

Needs to go `body > atom-workspace > atom-workspace-axis > atom-workspace-axis.CR-scrollable-view > atom-workspace-axis.CR-ribbon.(vert/horiz)`

This will allow us to better select the main view for calculations and have a container we can use for scroll events

**Comment by robobenklein** [comment]
Update note: actually goes
```
workspace > container.CR-primary > axis.RibbonContainer > Axis.Ribbon
```

**Comment by tkeyes25** [comment]
Cleaning up issues that are done
