### ISSUE TITLE
Hook for Window Size Change

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#14]
@tkeyes25 do you want this one? I just can't find the onDidChange() subscription for the Atom window being resized...

**Comment by robobenklein** [comment]
Apparently this package has it somewhere so let's steal that: https://github.com/cart/atom-hidpi

**Comment by tkeyes25** [comment]
onDidChangeScaleFlex() - what henley talked about

**Comment by tkeyes25** [comment]
I think I found the solution. I will open commit and open a PR here shortly @robobenklein

**Comment by tkeyes25** [comment]
This was found
