### ISSUE TITLE
See if flex layout will work with widths wider than the screen

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#17]
The PaneAxis already use a flex layout, so could perhaps we leverage that instead of doing pixel calculations for the viewport?

**Comment by tkeyes25** [comment]
Are we still doing pixel calcs? I thought I remember you finding a method to avoid it

**Comment by robobenklein** [comment]
Min Pixels per Patch still hasn't been finished. My unconfirmed approach is using the flex layout properties with a min-width in the hopes that we can then use width: as percentages of the container viewport.

**Comment by robobenklein** [comment]
Update: seems to work as intended.
