### ISSUE TITLE
Horizontal spacing style application

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#23]
Found this one by experimentation:

```
width = 100% * (number of total patches / number of visible patches)
```

Makes them scale nicely and we don't have to pixel-count.

**Comment by robobenklein** [comment]
![recorded](https://user-images.githubusercontent.com/5423266/52969456-73034200-337e-11e9-8373-200a9fa4d873.gif)

**Comment by tkeyes25** [comment]
Formula looks good, we prob don't need it to be an issue

**Comment by robobenklein** [comment]
#19
