### ISSUE TITLE
Setup github pages webpage

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#27]

**Comment by robobenklein** [comment]
Really complex example: https://github.com/robobenklein/robobenklein.github.io / https://unhexium.net/

Although probably we just need a single splash page and a dev history.

**Comment by robobenklein** [comment]
https://utk-se.github.io/CodeRibbon/

**Comment by tkeyes25** [comment]
I'll get something simple up later in the week for next meeting

**Comment by tkeyes25** [comment]
Where are some of your best gifs for the webpage? Could you post them in here @robobenklein

**Comment by tkeyes25** [comment]
Also, maybe add a theme so we could use Jekyll and get it up on no time @robobenklein I do not have access to settings I think

**Comment by tkeyes25** [comment]
I realize I could just do it locally with Jekyll, have not used it before

**Comment by tkeyes25** [comment]
I'm dumb, just ignore everything above. Just going to stick to Markdown. I thought I was supposed to use Jekyll for GitHub pages but realized they just use it to publish the content.

**Comment by robobenklein** [comment]
Use my site as an example, you can push full Jekyll sites and they will be rendered without any external theme required.

**Comment by tkeyes25** [comment]
Got it. Thank you for the confirmation and example. I'll begin to look into that and use it. Seems pretty cool

**Comment by tkeyes25** [comment]
@robobenklein Worked on this a bit on the plane, see what you'd like to add to the Acknowledgements page and you can push or just comment here

**Comment by robobenklein** [comment]
There are a lot of jekyll things you can use / take advantage of instead of hardcoding in html.

Mind if I do some pushes to gh-pages?

**Comment by tkeyes25** [comment]
Yea i dont mind

**Comment by robobenklein** [comment]
Pushed a bunch of changes to rework the jekyll things, like putting the nav and footer into includes, etc.

**Comment by tkeyes25** [comment]
Def had the nav and footer in includes before..? At least I thought so

**Comment by tkeyes25** [comment]
@robobenklein Saw your changes and they looked good. I actually did some of the similar fixes but forgot to push :/ 

I was confused however on the markdown part. Are we even using the html files? What was really the benefit in copying the html files, putting them in md in _pages?

**Comment by robobenklein** [comment]
In an ideal site, the content / text body would be completely separate from the source / html.

Those .html are just backups in case I missed something when cutting them up into the markdown files.

But now the header, footer, page template, etc are shared across the pages. I personally am biased towards writing all the content in markdown and having jekyll convert it to HTML for display in the page, so there wouldn't be almost any html in a .md.

**Comment by robobenklein** [comment]
Ah I think I see what the misunderstanding was, for GitHub pages you shouldn't commit the _site directory, since that's generated and built by jekyll on github's servers.

If you're running it locally, I recommend you use bundler,

```
bundle install/update
bundle exec jekyll serve --livereload
```

Then http://localhost:4000/CodeRibbon/ should work

**Comment by tkeyes25** [comment]
I think my main confusion was the HTML in a markdown, I did not know markdown allowed for that. Also, i tried markdown, but i had trouble with things like bootstrap since it was markdown
