### ISSUE TITLE
Overview: highlight pane on hover

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#28]
RIght now it is purple borders with blue borders on an active pane. If a user hovers over a pane, maybe shadow it or somthing, or have all other non-active patches be slightly darker

**Comment by robobenklein** [comment]
I was going to leave this to Atom to implement, since normally focus is designated with the blinking cursor and the borders are there for development only. We don't want to reduce the visibility of any code ever, so perhaps we need a different way to highlight focus.

**Comment by tkeyes25** [comment]
I agree with the visibility of the code. I guess I get confused about what occurs between dev and prod. Had no idea about the borders thing. Maybe ask how @AZHenley handled it

**Comment by robobenklein** [comment]
![image](https://user-images.githubusercontent.com/5423266/53282809-0a63ee80-370b-11e9-9193-6cf1ce5d433f.png)

on-hover box shadow for a patch

**Comment by tkeyes25** [comment]
We still need something to make it clear to the user that this is the active pane right now, both in an overview and in normal mode. Every patch looks the same active vs non-active in dev mode (only indication really is the cursor in the active pane). I could maybe look into making the active pane pop out some in a nice looking way

**Comment by robobenklein** [comment]
I'm not sure if this would be in-scope for this plugin anymore, since Atom itself would be the base reference for this.

Someone else's 2second hack for it: https://gist.github.com/crucialfelix/2d992845c8c05f28aba9

**Comment by tkeyes25** [comment]
Austin talked about this in meeting Wednesday. He said to just change the background color of the patch to be more noticeable, both in overview mode and normal

**Comment by tkeyes25** [comment]
This is mainly solved
