### ISSUE TITLE
Empty Patch Display

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#29]
Thoughts on what an empty patch should like besides what we have right now?

**Comment by tkeyes25** [comment]
Was thinking more of a "Add a file here" or maybe just "Empty"

**Comment by robobenklein** [comment]
@AZHenley how did patchworks handle this?

**Comment by tkeyes25** [comment]
@AZHenley Currently the following:

Non-overview: 
<img width="1495" alt="screen shot 2019-02-22 at 7 28 35 pm" src="https://user-images.githubusercontent.com/22582326/53278598-2ac68580-36d8-11e9-8348-75d67c7a2421.png">

Overview:
<img width="1491" alt="screen shot 2019-02-22 at 7 28 56 pm" src="https://user-images.githubusercontent.com/22582326/53278606-31ed9380-36d8-11e9-9d67-460382ad4d71.png">

**Comment by tkeyes25** [comment]
Decided to place the command-p command in empty patches to get recent folder recommendations

**Comment by tkeyes25** [comment]
Found [these shortcuts](https://github.com/nwinkler/atom-keyboard-shortcuts) for reference later, maybe walk through them and put them in the wiki

**Comment by tkeyes25** [comment]
[Here](https://github.com/atom/fuzzy-finder) is the source code for the file search that we want to place in empty patches. The command we want I believe is "fuzzy-finder:toggle-file-finder", but honestly unsure where to work for this in our project. 

Maybe code-ribbon-manager or code-ribbon-patch..? How can I detect if any patch is empty? Played around with the DOM to get the list of patches in a single ribbon container but did not get me anywhere helpful. Could I get some direction on where you think is the best place to fire this command if a patch is empty? @robobenklein

**Comment by robobenklein** [comment]
```
fp = atom.packages.getActivePackage("fuzzy-finder")
f = fp.mainModule.createProjectView()
```
![image](https://user-images.githubusercontent.com/5423266/56302079-0bac0900-6107-11e9-8a5d-7fb24d82e512.png)

**Comment by tkeyes25** [comment]
@robobenklein Unable to get any active package data from where I'm at in code. Any idea why?

For example, 
```
atom.packages.getActivePackeges()
```
returns an empty array

**Comment by tkeyes25** [comment]
@robobenklein Worked on this a bit on the plane, see what you'd like to add to the Acknowledgements page and you can push or just comment here

**Comment by robobenklein** [comment]
Well there is a misspelling there but...

```
atom.packages.getLoadedPackage('fuzzy-finder')
```

Because fuzzy-finder won't be `active` until it gets executed, but will be loaded.

**Comment by tkeyes25** [comment]
That did it, im dumb

**Comment by tkeyes25** [comment]
It seems like there cannot be multiple instances of PrjectView for the fuzzy finder. For instance, the bar only is shown on the last empty patch when I am creating an instance per empty patch. Then I'll go into the console, create a new one for another patch, then it switches, but there is never 2 or more. I feel like any code that wants to access the main workspace (as they probably do) proves to be a problem

**Comment by tkeyes25** [comment]
Also, idk how you managed to get the fuzzy finder to actually search for stuff, mine just says "Project is empty" no matter what I type

**Comment by tkeyes25** [comment]
We may need to revert back to the basic "Empty Patch" text for the trial since I could never get this to work to our liking.

I got the bar to appear, but only on the last empty patch, it seemed to not want to be on multiple patches. I think it has to do with the fact they try to access atom's main workspace center command, and in our application, it is kinda different

**Comment by robobenklein** [comment]
![image](https://user-images.githubusercontent.com/5423266/57336775-1d287580-70f5-11e9-8876-86cb9b276659.png)

**Comment by robobenklein** [comment]
tips are nice and fuzzy works better now
