### ISSUE TITLE
JS/TS/Coffee decision

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#3]
Decide which language to develop primarily in.

For dev speed sake, I am leaning towards raw JS since that will eliminate the need for the compile step, but Atom may have higher class support for Coffee as an install-time autoload.

I will vote against TypeScript since the 340 project had problems with people committing code that hadn't been transpiled.

**Comment by AZHenley** [comment]
I will vote against CoffeeScript because I don't like it and I think TS is killing it off anyway. JS is definitely the path of least resistance.

**Comment by robobenklein** [comment]
Pure JS it is!
