### ISSUE TITLE
Navigation Pane Disappears on Reload

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#30]
Window: Reload causes the Nav Pane to disappear for me in cr-patches

EDIT: 

Also, code from patches disappear

**Comment by tkeyes25** [comment]
I am guessing we just have not saved the state from the serializable patches on reload, considering we are stilling developing on patches

**Comment by robobenklein** [comment]
If you launch with the --no-window-state flag it will always delete the state on reload. This doesn't occur in production use.
