### ISSUE TITLE
Disable split pane menu item

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#31]
I imagine split should create new pane but it just creates space for one and not an editable patch

**Comment by robobenklein** [comment]
The pane "split" feature will be completely disabled in the final version, along with close pane.

**Comment by robobenklein** [comment]
Well it's 'disabled' but is still there...

**Comment by tkeyes25** [comment]
So should this be closed? If we are not going to use it....

**Comment by robobenklein** [comment]
No, the menu item is still shown even tho it doesn't do anything

**Comment by tkeyes25** [comment]
Do we want to remove it? What do you see for its future use? Maybe add column left/right?

**Comment by robobenklein** [comment]
Well this issue's problem is somehow removing a menu item which we both don't own and don't have access to, so right now I don't know of the solution.

**Comment by robobenklein** [comment]
Got it, doing a search through the context menu items and removing those.

**Comment by robobenklein** [comment]
These have been mitigated for the most part
