### ISSUE TITLE
Add commands to assist creating patches in development

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#32]
Kinda tedious to go to settings to reset my number of patches. How about a menu option or something of the sort? 

Set number of patches > (user enters number)

Set min pix width > (user enters number)

**Comment by robobenklein** [comment]
Sure, although this will be development mode only, since in the end patches will be given to the user as they open files.

**Comment by tkeyes25** [comment]
I guess we're done with this since we merged my PR
