### ISSUE TITLE
Empty Scroll Bar on Start up in 'Dev'

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#34]
Checked out dev branch and this happened... 

<img width="1276" alt="screen shot 2019-02-24 at 3 27 24 pm" src="https://user-images.githubusercontent.com/22582326/53304917-e8708600-3848-11e9-9472-00f16676caa1.png">

**Comment by robobenklein** [comment]
This is definitely bug lol, will investigate

**Comment by robobenklein** [comment]
With the new dev does this still happen?

**Comment by tkeyes25** [comment]
It does not! I'll let you close if you decide
