### ISSUE TITLE
New GIF for Landing Page

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#38]
New GIF for the website landing page instead of the hacky one

**Comment by tkeyes25** [comment]
My mac usually can handle 4k at home... :-( 

![CR-Example](https://user-images.githubusercontent.com/22582326/55998808-d5493680-5c8d-11e9-96b1-6479f8584b9d.gif)

**Comment by tkeyes25** [comment]
Could we maybe use AZH's monitor on Wednesday?

**Comment by robobenklein** [comment]
Will @AZHenley be here on Wednesday?

**Comment by tkeyes25** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22582326/56855649-bfd43d80-6918-11e9-9cc7-02295f7ee2e9.gif)

**Comment by tkeyes25** [comment]
![output](https://user-images.githubusercontent.com/22582326/56878204-d8c81600-6a20-11e9-89f6-d3a2a47fa21f.gif)
