### ISSUE TITLE
Adding New Patches discoloring 

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#39]
Seems like it is buggy when I toggle the command to add patches now with the new empty patch design. I add some, and the patches are back to the purple border. Let me know if you were aware of this and need videos @robobenklein 

I did the following and got different results
```
atom -d  . --clear-window-state
```
This created however many patches I had serialized or saved (with the correct form of an empty patch), then when I add/ close patches, the patches turn purple.

```
atom -d .
```

This mainly just made all of my previous empty patches purple.

I am on the dev branch

**Comment by robobenklein** [comment]
Aw shoot good bug report...

will investigate

**Comment by tkeyes25** [comment]
I did not see any commits towards this, but now the command does not work on dev branch. Quite interesting

**Comment by robobenklein** [comment]
There's no command for adding patches anymore because it's a dynamic implementation now. It'll create and remove patches as needed when you run CR update.

Also I think this bug is fixed, should be consistent now.

**Comment by tkeyes25** [comment]
For CR-Update, is it run automatically? Or do I need to run it manually? What would be the command? @robobenklein

**Comment by robobenklein** [comment]
In #41 it is getting run automatically
