### ISSUE TITLE
Atom: Hide tabs

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeRibbon#4]
Hide the tabs of a pane so that we can put our own stuff there.

**Comment by tkeyes25** [comment]
From reading last night, I found that you can disable the tabs default package in settings if that is the goal of this issue. I'm sure we could disable programmatically when our package is active

**Comment by robobenklein** [comment]
Seems good, then we'll want to add in our own custom pane handles and titling. Not sure how to implement pane moves without it, so this will require more research.

**Comment by tkeyes25** [comment]
As of right now, tabs are either disabled or enabled on command toggle(), and are kept the way the user last leaves it (so if I had them disabled and reloaded screen, they still are disabled). Here, I think we should save the state, and if they are enabled, ALWAYS disable them on activation of the package

**Comment by tkeyes25** [comment]
@robobenklein Should we do a PR or keep it open? I got your message about the serializable interface and that makes sense. As of right now, it will disable/enable correctly within sync of the popup window that says "The CodeRibbon package is Alive! It\'s ALIVE!"

**Comment by robobenklein** [comment]
Go ahead and open a PR, I like to have them open early anyways as 'tracking' PRs so that progress can be seen. I would have had one already if I was following my norm of committing multiple times a day...

**Comment by tkeyes25** [comment]
Closing for further design assessment
