### ISSUE TITLE
Initial Startup Patch Number Not Filled

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#44]
Kinda buggy when I start it up with the new patch number calc on cr_update. I was on my empty-patch branch if that is the problem and i am behind on functionality (although, I remember quota being merged before I made my branch)

<img width="1273" alt="Screen Shot 2019-03-31 at 11 11 18 PM" src="https://user-images.githubusercontent.com/22582326/55301377-512fbd00-540a-11e9-9f5d-77df199acdb9.png">

**Comment by tkeyes25** [comment]
I believe ```--clear-window-state``` is what produces this now. If i start up a blank workspace w/o that flag, all good. With it, not so good.

**Comment by robobenklein** [comment]
@tkeyes25 wanna re-test this with the latest on #41 ?

**Comment by tkeyes25** [comment]
I still think ```--clear-window-state``` is causing the bug. Every time I close atom and start it back up with that, the following bug is produced

**Comment by robobenklein** [comment]
Gonna merge #41 then see if it's still an issue

**Comment by tkeyes25** [comment]
Good stuff seems to work now. Closing
