### ISSUE TITLE
Capturing Commands or Events in Atom

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#45]
SO CONFUSED ON THIS. Basically, I want to execute a command for #29. Also, down the road, for example, we would want to capture events like CMD/CNTL-N for new patches, so might as well talk about it now @robobenklein

**Comment by robobenklein** [comment]
Keys are bound to event handles, for example:

![image](https://user-images.githubusercontent.com/5423266/55337425-a8667980-546c-11e9-8f62-c11703cb6182.png)

Even normal keys (abc...) are all bound, and applications have different priority levels to determine which action will be executed in which context.

We would register our own event handler for our specific keypresses that would be bound to an Atom command: https://atom.io/docs/api/v1.35.1/CommandRegistry

**Comment by robobenklein** [comment]
For registration of these commands, we'll probably want a manager and a default keymap supplied with the plugin: https://atom.io/docs/api/v1.35.1/KeymapManager

**Comment by tkeyes25** [comment]
Can we address this in the meeting? Kinda confused

**Comment by tkeyes25** [comment]
Not really an issue
