### ISSUE TITLE
Command/Cntl-W breaks Atom

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#49]
Key combination closes out a tab, which then breaks our application. 

AZH and I talked about it the last meeting, and we thought all we had to do was capture the command event, and simply ignore it

**Comment by tkeyes25** [comment]
Command is: 
```
core:close
```

**Comment by tkeyes25** [comment]
https://discuss.atom.io/t/prevent-cmd-w-from-closing-a-pane/16283

**Comment by robobenklein** [comment]
Ok so does it close a tab that breaks it, or does it close a pane that breaks it? I should think that closing a tab should not have any problems - otherwise there's more work still...

**Comment by tkeyes25** [comment]
Well before it crashes the app, but now it will not let me select patches. Maybe you give it a go on dev? It deletes panes and tabs

**Comment by tkeyes25** [comment]
This seems to be fine now. Closing
