### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by tkeyes25** [utk-se/CodeRibbon#50]
Horizontal scrolling seems to be buggy. Does not know whether to scroll over entire code ribbon or scroll within whatever patch the mouse is over

May need to address this before #22 

![horizontal_scrolling (1)](https://user-images.githubusercontent.com/22582326/56478056-11dd1500-647a-11e9-812c-e616ce10bfd2.gif)

**Comment by tkeyes25** [comment]
Well this GIF is pretty rough but whatever

**Comment by robobenklein** [comment]
What should the desired behaviour be here? Should the inner view scroll first before the outer, or should the outer view lock the scroll during the scroll activity?

**Comment by tkeyes25** [comment]
Honestly, do not know. On one hand, the user should be able to easily navigate the ribbon. On the other hand, it is quite difficult to actually do work on a smaller screen or laptop. This would not be a problem on larger screens with larger patches, BUT we would still need to easily differentiate between the tww

**Comment by tkeyes25** [comment]
Maybe only allow that trackpad horizontal scrolling for active patches? So if the mouse is over the active patch, horizontal scroll on the patch, other than that, all horizontal scrolling for the ribbon. This way, they can select and then navigate the code

**Comment by AZHenley** [comment]
Hmmmm unclear the best route. If the ribbon is easy to navigate in other ways, then perhaps it is best to keep horizontal scrolling only for scrolling within a patch.

**Comment by tkeyes25** [comment]
@robobenklein You agree?

**Comment by tkeyes25** [comment]
I'd say the ribbon is easy to navigate with the scroll bar

**Comment by robobenklein** [comment]
Well we don't really have a keybinds decision for what the stepped left/right should be.

Depending on what that is, it could be easier than the mouse.

**Comment by robobenklein** [comment]
Well this issue is very difficult since it's a problem with HTML rendering and not anything we have very good control over.

Chrome, Firefox, etc all also have this kind of issue, Chrome had to implement an (IMO awful) solution that locked scroll targets based on activity, and I've yet to find a good fix for electron that we can use in an Atom plugin...

**Comment by tkeyes25** [comment]
Dang! We will need to come to a decision on keybinds then to navigate patches

**Comment by robobenklein** [comment]
https://github.com/atom/atom/pull/20347

**Comment by robobenklein** [comment]
atom v.1.47.0 CR v0.0.33
