### ISSUE TITLE
Enable Fullscreen of Selected Patch

### ISSUE THREAD

**Issue by pbstrein** [utk-se/CodeRibbon#97]
Is there a way to zoom into a selected patch to take in the full screen? I often like having my code take up the entire screen while coding, but then zoom out to other patches as needed. 

For example, Tmux has an option to make a pane full screen (hiding the other screens.) Then when done working fullscreen, you can zoom back out to how the screen was before. 

[This blog post](https://ostechnix.com/how-to-zoom-tmux-panes-for-better-text-visibility/) has a GIF showing what it looks like in Tmux. Having something similar for patches would improve my developer productivity.

**Comment by robobenklein** [comment]
There are still remnants of code laying about for what used to be "Focus" where a single patch would grow to the screen size.

I think some other implementations call it "Zen" mode, but that also implies that panels / docks / things outside the center of the workspace are hidden as well.

Does something simple like this work?

https://user-images.githubusercontent.com/5423266/120013619-f58ff880-bfae-11eb-8848-f8b64727a075.mp4

Probably will have something like it pushed today.

**Comment by pbstrein** [comment]
Yes! That would work great!

**Comment by robobenklein** [comment]
Any suggestion for a better name for the command and a shortcut key?

**Comment by pbstrein** [comment]
Any of these work for me, and am open to other ideas as well. 
Name:
Zoom Patch (this is my favorite)
Zoom Pane
Fullscreen
Zoom
Full Zoom
Full Zoom Patch

Shortcut Key - i would stick to what other IDEs do. If there is one in Atom that fits, maybe that. Here are other ones I am aware of:
Tmux - Ctrl + B, Z
VSCode - Ctrl + K, Z
Visual Studio - Alt + Shift + Enter

Out of my small sample size, doing something with Z seems consistent with other IDEs/terminals.

**Comment by robobenklein** [comment]
Just published the `Zoom Patch` command, let me know if anything should be changed.

`Ctrl-K Z` for shortcut, becomes un-zoomed when the patch loses focus. (like when using Ctrl-Tab or scrolling elsewhere and activating a different patch)

**Comment by pbstrein** [comment]
Downloaded the update, works great on my end! Great turnaround time! Thanks!
